club_search/urls.py
from django.urls import path

from club_search import views

app_name = "club_search"

urlpatterns = [
    path("", views.club_list_all, name="club_list_all"),
    path("<int:club_id>/", views.club_detail, name="club_detail"),
    path("<str:club_department>/", views.club_list, name="club_list"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from club_search import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("club/", include('club_search.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

club_search/models.py
from django.db import models


# Create your models here.
class Club(models.Model):
    name = models.CharField(max_length=50)
    logo = models.ImageField(null=True, blank=True, upload_to="images/")
    sort = models.CharField(max_length=50)
    department = models.CharField(max_length=50)
    tag = models.TextField(null=True, blank=True)
    manager = models.CharField(null=True, blank=True, max_length=50)
    manager_call = models.CharField(null=True, blank=True, max_length=50)
    introduction = models.TextField(null=True, blank=True)
    recruit_period = models.CharField(null=True, blank=True, max_length=50)
    recruit_number = models.CharField(null=True, blank=True, max_length=50)
    recruit_way = models.CharField(null=True, blank=True, max_length=50)
    activity_period = models.CharField(null=True, blank=True, max_length=50)

    def __str__(self):
        return self.name

club_search/views.py
from django.shortcuts import render, get_object_or_404

from club_search.models import Club


# Create your views here.
def index(request):
    context = {
        "navbar_active": "홈",
    }

    return render(request, 'club_search/index.html', context)


def club_list(request, club_department):
    if club_department == "com_edu":
        club_department = "컴퓨터교육과"
    elif club_department == "edu":
        club_department = "교육학과"
    elif club_department == "math_edu":
        club_department = "수학교육과"
    elif club_department == "han_edu":
        club_department = "한문교육과"
    else:
        club_department = "사범대학"

    search = request.GET.get('search', None)
    sort = request.GET.get('sort', None)

    if search and sort:
        clubs = Club.objects.filter(department=club_department, name__contains=search, sort=sort)
    elif search and not sort:
        clubs = Club.objects.filter(department=club_department, name__contains=search)
    elif not search and sort:
        clubs = Club.objects.filter(department=club_department, sort=sort)
    else:
        clubs = Club.objects.filter(department=club_department)

    context = {
        "header_title": club_department,
        "navbar_active": club_department,
        "club_list": clubs,
        "dropdown_selected": sort,
    }

    return render(request, 'club_search/club_list.html', context)


def club_detail(request, club_id):
    club = Club.objects.get(id=club_id)

    context = {
        "header_title": club.department,
        "navbar_active": club.department,
        "club": club,
    }

    return render(request, 'club_search/club_detail.html', context)


def club_list_all(request):
    search = request.GET.get('search', '')

    searched_clubs = Club.objects.filter(name__contains=search)

    context = {
        "header_title": "검색",
        "navbar_active": "홈",
        "club_list": searched_clubs,
    }

    return render(request, 'club_search/club_list.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}?after">
        <link rel="stylesheet" type="text/css" href="{% static 'navbar.css' %}?after">
        <link rel="stylesheet" type="text/css" href="{% static 'header.css' %}?after">
        <link rel="stylesheet" type="text/css" href="{% static 'search-form.css' %}?after">
        <link rel="stylesheet" type="text/css" href="{% static 'footer.css' %}?after">
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}?after">
        <title>EDU:CLUB</title>
    </head>
    <body>
        {% include "navbar.html" %}
        <main class="main">
            {% block content %}
            {% endblock %}
        </main>
        {% include "footer.html" %}
        <script src="{% static 'bootstrap.js' %}"></script>
        <script src="https://code.jquery.com/jquery-3.6.2.js" integrity="sha256-pkn2CUZmheSeyssYw3vMp1+xyub4m+e+QK4sQskvuo4=" crossorigin="anonymous"></script>

        <script>
            $(function () {
                $(document).scroll(function () {
                    var $nav = $(".navbar");
                    $nav.toggleClass('scrolled', $(this).scrollTop() > $nav.height());
                });
            });
        </script>
    </body>
</html>

templates/club_search/club_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="header min-size">
    <div class="header-content">
        <div class="header-title">
            <h1 class="big-header-title mb-4">{{ header_title }}</h1>
        </div>
    </div>
</div>
<div class="container-fluid pt-5">
    <div class="club-info-wrapper">
        <div class="club-info">
            <div class="club-logo">
                {% if club.logo %}
                <img class="club-logo-img" src="{{ club.logo.url }}" alt="{{ club.name }}">
                {% else %}
                <img class="club-logo-img" src="/static/default-logo.jpg" alt="{{ club.name }}">
                {% endif %}
            </div>
            <div class="club-summary d-flex flex-column justify-content-between">
                <div>
                    <h5>{{ club.sort }}</h5>
                    <h1 class="fw-normal">{{ club.name }}</h1>
                </div>
                <h6>대표자 : {{ club.manager|default_if_none:"OOO" }} ({{ club.manager_call|default_if_none:"010-0000-0000" }})</h6>
                {% if club.tag %}
                <h6> {{ club.tag }}</h6>
                {% else %}
                <h6>#{{ club.name }} #{{ club.sort }}</h6>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="recruit-info-wrapper">
        <div class="recruit-info">
            <div class="recruit-info-item">
                <i class="bi bi-calendar-date"></i>
                <div class="recruit-info-detail">
                    <h6>모집시기</h6>
                    {% if club.recruit_period %}
                    <p>{{ club.recruit_period }}</p>
                    {% else %}
                    <p>미결</p>
                    {% endif %}
                </div>
            </div>
            <div class="recruit-info-item">
                <i class="bi bi-people"></i>
                <div class="recruit-info-detail">
                    <h6>모집인원</h6>
                    {% if club.recruit_number %}
                    <p>{{ club.recruit_number }}</p>
                    {% else %}
                    <p>미결</p>
                    {% endif %}
                </div>
            </div>
            <div class="recruit-info-item">
                <i class="bi bi-pencil"></i>
                <div class="recruit-info-detail">
                    <h6>모집방식</h6>
                    {% if club.recruit_way %}
                    <p>{{ club.recruit_way }}</p>
                    {% else %}
                    <p>미결</p>
                    {% endif %}
                </div>
            </div>
            <div class="recruit-info-item">
                <i class="bi bi-watch"></i>
                <div class="recruit-info-detail">
                    <h6>활동기간</h6>
                    {% if club.activity_period %}
                    <p>{{ club.activity_period }}</p>
                    {% else %}
                    <p>미결</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% if club.introduction %}
    <div class="d-flex flex-column align-items-center">
        <div class="col-10 col-md-8 col-lg-6">
            <h5 class="text-center mb-3 fw-bold">소개</h5>
            <p class="px-0 px-md-5">{{ club.introduction }}</p>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

templates/club_search/club_list.html
{% extends 'base.html' %}
{% block content %}
<div class="header min-size">
    <div class="header-content">
        <div class="header-title">
            <h1 class="big-header-title mb-4">{{ header_title }}</h1>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="club-section col-12 col-md-10">
        <form id="search-form" class="search-form" method="GET">
            <select name="sort" id="sort" class="dropdown" onchange="this.form.submit()">
                <option value="">전체</option>
                {% if dropdown_selected == '학회' %}
                <option value="학회" selected>학회</option>
                {% else %}
                <option value="학회">학회</option>
                {% endif %}
                {% if dropdown_selected == '소모임' %}
                <option value="소모임" selected>소모임</option>
                {% else %}
                <option value="소모임">소모임</option>
                {% endif %}
            </select>
            <div class="search">
                <i class="search-icon bi bi-search"></i>
                <input class="search-input" type="text" name="search" placeholder="검색" autocomplete="off" />
            </div>
        </form>
        <div class="club-list">
            {% if club_list %}
            {% for club in club_list %}
            <div class="club-item" onclick="location.href='{% url 'club_search:club_detail' club.id %}'">
                {% if club.logo %}
                <img src="{{ club.logo.url }}" alt="{{ club.name }}">
                {% else %}
                <img src="/static/default-logo.jpg" alt="{{ club.name }}">
                {% endif %}
                <h2>{{ club.name }}</h2>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/club_search/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid px-0">
    <div class="header">
        <div class="header-content">
            <div class="header-title">
                <h2 class="small-header-title">나에게 딱 맞는</h2>
                <h1 class="big-header-title">동아리를 찾아보세요!</h1>
            </div>
            <form class="search-form" action="{% url 'club_search:club_list_all' %}" method="GET">
                <div class="search">
                    <i class="search-icon bi bi-search"></i>
                    <input class="search-input" type="text" name="search" placeholder="검색" autocomplete="off" />
                </div>
            </form>
        </div>
    </div>
    <div class="landing">
        <div class="intro">
            <p>갓 입학한 <span>새내기</span>도 🐣</p>
            <p>전역한 <span>복학생</span>도 🫡</p>
            <p>졸업이 아쉬운 <span>고학번</span>도 🤦‍️</p>
            <p>내가 들어가고 싶은 <span class="highlight">동아리</span>의 정보를 한눈에!</p>
        </div>
    </div>
</div>
{% endblock %}

templates/footer.html
<footer class="footer">
  <div class="footer-copyright">
    <i class="bi bi-c-circle"></i> CMD. All rights reserved.
  </div>
  <div class="footer-host">
      <span>Team Name : 고전명저북:CLUB</span>
  </div>
</footer>

templates/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">EDU:CLUB</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if navbar_active == '홈' %} active {% endif %}" href="{% url 'index' %}">홈</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if navbar_active == '사범대학' %} active {% endif %}" href="{% url 'club_search:club_list' 'edu_group' %}">사범대학</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if navbar_active == '컴퓨터교육과' %} active {% endif %}" href="{% url 'club_search:club_list' 'com_edu' %}">컴퓨터교육과</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if navbar_active == '교육학과' %} active {% endif %}" href="{% url 'club_search:club_list' 'edu' %}">교육학과</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if navbar_active == '수학교육과' %} active {% endif %}" href="{% url 'club_search:club_list' 'math_edu' %}">수학교육과</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if navbar_active == '한문교육과' %} active {% endif %}" href="{% url 'club_search:club_list' 'han_edu' %}">한문교육과</a>
                </li>
            </ul>
        </div>
    </div>
</nav>